### ISSUE TITLE
Version 0.6.2 does not support JDK17, prompting compilation to class file version 64.0 (JDK20)

### ISSUE THREAD

**Issue by Yang-Deyi** [Scogun/komm#15]
java.lang.UnsupportedClassVersionError: KOMMProcessorProvider has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by Scogun** [comment]
Hello @Yang-Deyi!
Thank you for the information.
Please try new version `0.7.4` (it will be available soon).
It also includes `Exposed` plugin.
