### ISSUE TITLE
invalid exception ‘com.ucasoft.komm.processor.exceptions.KOMMException: The class N is not a Kotlin class!’

### ISSUE THREAD

**Issue by Spinoza0** [Scogun/komm#21]
Why is this exception thrown for the class 
@Serializable
data class N(
    val field1: Int,
    val field2: Int,
)
?

I tried using @KOMMMap(to = [N::class]) and got an exception.

**Comment by Scogun** [comment]
Hello @Spinoza0!
Thank you that you use **KOMM**.
I tried to reproduce the issue but was unsuccessful.
Could you provide a repo where the issue is reproducible?
If not - could you specify:

1. Versions:
    1. Kotlin
    2. Serialisable plugin
    3. KOMM
2. Full specification:
    1. Source class
    2. Destination class
3. Target (MacOS, Windows etc.)

**Comment by Spinoza0** [comment]
Versions:
Kotlin: 2.0.20
Serialisable plugin: kotlinx-serialization-json 1.7.1
KOMM: 0.10.3

Full specification:
Source class:
```
@KOMMMap(to = [N::class])
@Serializable
internal class NResponse(
    @SerialName("positive") val positiveCount: Int,
    @SerialName("negative") val negativeCount: Int,
)

```

Destination class:
```
@Serializable
data class N(
    val positiveCount: Int,
    val negativeCount: Int,
)
```

Target (MacOS, Windows etc.): Android

**Comment by Scogun** [comment]
So, seems the issue is clear: KOMM 0.10.3 is not suitable for Kotlin 2.\*.
I will prepare additional version with Kotlin 2.\* support.
